"""Crear tablas declaracion renta

Revision ID: 2cbd3c8f65a5
Revises: 199d774c8c57
Create Date: 2026-08-28 17:01:04.687333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cbd3c8f65a5'
down_revision: Union[str, Sequence[str], None] = '199d774c8c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Terceros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('ingresos_total', sa.Float(), nullable=True),
    sa.Column('retenciones_practicadas', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Terceros_id'), 'Terceros', ['id'], unique=False)
    op.create_index(op.f('ix_Terceros_nit'), 'Terceros', ['nit'], unique=True)
    op.create_table('activos_fijos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor_compra', sa.Float(), nullable=True),
    sa.Column('impuesto_pagado', sa.Float(), nullable=True),
    sa.Column('vida_util', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activos_fijos_id'), 'activos_fijos', ['id'], unique=False)
    op.create_table('cuentas_bancarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad', sa.String(length=100), nullable=False),
    sa.Column('numero_cuenta', sa.String(length=50), nullable=False),
    sa.Column('rendimientos_financieros', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuentas_bancarias_id'), 'cuentas_bancarias', ['id'], unique=False)
    op.create_table('declaraciones_anteriores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('anticipo', sa.Float(), nullable=True),
    sa.Column('saldo_a_favor', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_declaraciones_anteriores_id'), 'declaraciones_anteriores', ['id'], unique=False)
    op.create_table('deudas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('interes_pagado_en_el_ano', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deudas_id'), 'deudas', ['id'], unique=False)
    op.create_table('gastos_operativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('valor_total_en_el_ano', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gastos_operativos_id'), 'gastos_operativos', ['id'], unique=False)
    op.create_table('inversiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('rendimientos', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inversiones_id'), 'inversiones', ['id'], unique=False)
    op.create_table('nominas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado', sa.String(length=255), nullable=False),
    sa.Column('salario_mensual', sa.Float(), nullable=True),
    sa.Column('prestaciones_sociales_anual', sa.Float(), nullable=True),
    sa.Column('aportes_seg_social_anual', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nominas_id'), 'nominas', ['id'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('compras_total', sa.Float(), nullable=True),
    sa.Column('retenciones_sufridas', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_index(op.f('ix_proveedores_nit'), 'proveedores', ['nit'], unique=True)
    op.create_table('retenciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('comprobante', sa.String(length=50), nullable=False),
    sa.Column('nit_tercero', sa.String(length=20), nullable=False),
    sa.Column('nombre_tercero', sa.String(length=255), nullable=False),
    sa.Column('perfil_tributario', sa.String(length=50), nullable=True),
    sa.Column('concepto_contable', sa.String(length=100), nullable=False),
    sa.Column('concepto_dian', sa.String(length=10), nullable=False),
    sa.Column('base_gravable', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tarifa', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('valor_retenido', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cuenta_pasivo', sa.String(length=20), nullable=False),
    sa.Column('tipo_retencion', sa.String(length=20), nullable=True),
    sa.Column('formato_asignado', sa.String(length=10), nullable=True),
    sa.Column('concepto_exogena', sa.String(length=10), nullable=True),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_retenciones_fecha_comprobante', 'retenciones', ['fecha', 'comprobante'], unique=False)
    op.create_index(op.f('ix_retenciones_id'), 'retenciones', ['id'], unique=False)
    op.create_index(op.f('ix_retenciones_nit_tercero'), 'retenciones', ['nit_tercero'], unique=False)
    op.create_index(op.f('ix_retenciones_periodo'), 'retenciones', ['periodo'], unique=False)
    op.create_index('ix_retenciones_periodo_nit', 'retenciones', ['periodo', 'nit_tercero'], unique=False)
    op.create_index('ix_retenciones_tipo_periodo', 'retenciones', ['tipo_retencion', 'periodo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_retenciones_tipo_periodo', table_name='retenciones')
    op.drop_index('ix_retenciones_periodo_nit', table_name='retenciones')
    op.drop_index(op.f('ix_retenciones_periodo'), table_name='retenciones')
    op.drop_index(op.f('ix_retenciones_nit_tercero'), table_name='retenciones')
    op.drop_index(op.f('ix_retenciones_id'), table_name='retenciones')
    op.drop_index('ix_retenciones_fecha_comprobante', table_name='retenciones')
    op.drop_table('retenciones')
    op.drop_index(op.f('ix_proveedores_nit'), table_name='proveedores')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_nominas_id'), table_name='nominas')
    op.drop_table('nominas')
    op.drop_index(op.f('ix_inversiones_id'), table_name='inversiones')
    op.drop_table('inversiones')
    op.drop_index(op.f('ix_gastos_operativos_id'), table_name='gastos_operativos')
    op.drop_table('gastos_operativos')
    op.drop_index(op.f('ix_deudas_id'), table_name='deudas')
    op.drop_table('deudas')
    op.drop_index(op.f('ix_declaraciones_anteriores_id'), table_name='declaraciones_anteriores')
    op.drop_table('declaraciones_anteriores')
    op.drop_index(op.f('ix_cuentas_bancarias_id'), table_name='cuentas_bancarias')
    op.drop_table('cuentas_bancarias')
    op.drop_index(op.f('ix_activos_fijos_id'), table_name='activos_fijos')
    op.drop_table('activos_fijos')
    op.drop_index(op.f('ix_Terceros_nit'), table_name='Terceros')
    op.drop_index(op.f('ix_Terceros_id'), table_name='Terceros')
    op.drop_table('Terceros')
    # ### end Alembic commands ###
