"""Crear tablas declaracion renta

Revision ID: 7d407a86aa03
Revises: d0b16476be3b
Create Date: 2026-08-28 16:45:39.681212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d407a86aa03'
down_revision: Union[str, Sequence[str], None] = 'd0b16476be3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retenciones_fecha_comprobante'), table_name='retenciones')
    op.drop_index(op.f('ix_retenciones_id'), table_name='retenciones')
    op.drop_index(op.f('ix_retenciones_nit_tercero'), table_name='retenciones')
    op.drop_index(op.f('ix_retenciones_periodo'), table_name='retenciones')
    op.drop_index(op.f('ix_retenciones_periodo_nit'), table_name='retenciones')
    op.drop_table('retenciones')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retenciones',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fecha', sa.DATETIME(), nullable=False),
    sa.Column('comprobante', sa.VARCHAR(length=50), nullable=False),
    sa.Column('nit_tercero', sa.VARCHAR(length=20), nullable=False),
    sa.Column('nombre_tercero', sa.VARCHAR(length=255), nullable=False),
    sa.Column('perfil_tributario', sa.VARCHAR(length=50), nullable=True),
    sa.Column('concepto_contable', sa.VARCHAR(length=100), nullable=False),
    sa.Column('concepto_dian', sa.VARCHAR(length=10), nullable=False),
    sa.Column('base_gravable', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('tarifa', sa.NUMERIC(precision=10, scale=4), nullable=False),
    sa.Column('valor_retenido', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('cuenta_pasivo', sa.VARCHAR(length=20), nullable=False),
    sa.Column('formato_asignado', sa.VARCHAR(length=10), nullable=True),
    sa.Column('concepto_exogena', sa.VARCHAR(length=10), nullable=True),
    sa.Column('periodo', sa.VARCHAR(length=7), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=20), server_default=sa.text("'procesado'"), nullable=True),
    sa.Column('observaciones', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('tipo_retencion', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retenciones_periodo_nit'), 'retenciones', ['periodo', 'nit_tercero'], unique=False)
    op.create_index(op.f('ix_retenciones_periodo'), 'retenciones', ['periodo'], unique=False)
    op.create_index(op.f('ix_retenciones_nit_tercero'), 'retenciones', ['nit_tercero'], unique=False)
    op.create_index(op.f('ix_retenciones_id'), 'retenciones', ['id'], unique=False)
    op.create_index(op.f('ix_retenciones_fecha_comprobante'), 'retenciones', ['fecha', 'comprobante'], unique=False)
    # ### end Alembic commands ###
