"""crear tabla mapping_rules

Revision ID: 1ed6953c0420
Revises: 
Create Date: 2026-08-13 16:13:37.453127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed6953c0420'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puc_code', sa.String(length=20), nullable=False),
    sa.Column('puc_name', sa.String(length=255), nullable=True),
    sa.Column('exogena_format', sa.String(length=10), nullable=False),
    sa.Column('exogena_concept', sa.String(length=10), nullable=False),
    sa.Column('exogena_concept_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_rules_id'), 'mapping_rules', ['id'], unique=False)
    op.create_index(op.f('ix_mapping_rules_puc_code'), 'mapping_rules', ['puc_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mapping_rules_puc_code'), table_name='mapping_rules')
    op.drop_index(op.f('ix_mapping_rules_id'), table_name='mapping_rules')
    op.drop_table('mapping_rules')
    # ### end Alembic commands ###
